### ISSUE TITLE
Error: pdfimages version 3.04

### ISSUE THREAD

**Issue by dcaud** [sckott/pdfimager#1]
Following the vignette, I get an error:

```
library("pdfimager")
x <- system.file("examples/BachmanEtal2020.pdf", package="pdfimager")
pdimg_meta(x)
```

Results in:

    "Error: pdfimages version 3.04"

I'm using Mac, Darwin, 20.5.0.

**Comment by sckott** [comment]
Thanks for the report @dcaud Can you run that again, then immediately after run `traceback()` and share the output of that here?

also, what does `which pdfimages` run on the command line give you?

**Comment by dcaud** [comment]
Error is gone!

**Comment by sckott** [comment]
great!
