### ISSUE TITLE
Saving images in jpeg or png rather than pmp format from pdimg_images() - is this possible at all, the help file seems to suggest it, but is not very clear how to add options to a pdimg_images() call. Thanks !

### ISSUE THREAD

**Issue by Zagamog** [sckott/pdfimager#3]
<details> <summary><strong>Session Info</strong></summary>

```r

```
</details>

**Comment by sckott** [comment]
you can run `pdimg_help()` to get the help docs from `pdfimages` so you can see what flags are available

for the `pdimg_images` function you can pass in additional command line args 

i've no idea about the format options, sorry

**Comment by Zagamog** [comment]
Scott: my apologies if this is not the correct forum. So pdimg_help() provides the command line option  of "-png  : change the default output format to PNG" . But I am running the pdimg_images("path to my pdf file") command as part of an R script file, what I did not understand is how to pass the -png command line option in my R script file, the provided R script examples do not include the use of the options. Thanks !
