### ISSUE TITLE
Error in pdfimages_exists() : `pdfimages` not found, see ?pdfimg_meta

### ISSUE THREAD

**Issue by b2thewalker** [sckott/pdfimager#6]
Hi

Took me some time to work out how to install poppler onto my windows pc but I got there in the end using msys2.org, so I can now see and call all the pdfimager functions, however whenever I do I always get this same error for all of them: "Error in pdfimages_exists() : `pdfimages` not found, see ?pdfimg_meta". So it appears pdfimages has not been installed with poppler?

Any advice would be appreciated.

**Comment by sckott** [comment]
Thanks for the report. Can you use `pdfimages` from your terminal? What does `system("pdfimages")` in R give you?

**Comment by b2thewalker** [comment]
Hi Sckott, thanks for quick reply.

From PowerShell, if I run pdfimages i get:

pdfimages version 24.07.0
Copyright 2005-2024 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2011, 2022 Glyph & Cog, LLC
Usage: pdfimages [options] <PDF-file> <image-root>
  -f <int>                 : first page to convert
  -l <int>                 : last page to convert
  -png                     : change the default output format to PNG
  -tiff                    : change the default output format to TIFF
  -j                       : write JPEG images as JPEG files
  -jp2                     : write JPEG2000 images as JP2 files
  -jbig2                   : write JBIG2 images as JBIG2 files
  -ccitt                   : write CCITT images as CCITT files
  -all                     : equivalent to -png -tiff -j -jp2 -jbig2 -ccitt
  -list                    : print list of images instead of saving
  -opw <string>            : owner password (for encrypted files)
  -upw <string>            : user password (for encrypted files)
  -p                       : include page numbers in output file names
  -print-filenames         : print image filenames to stdout
  -q                       : don't print any messages or errors
  -v                       : print copyright and version info
  -h                       : print usage information
  -help                    : print usage information
  --help                   : print usage information
  -?                       : print usage information

system("pdfimages") from R gives:
Cannot open shim file for read.
Could not read shim file.

Note that since my post yesterday I have also installed poppler using scoop, so it appears I have two instances of it now:
C:\msys64\mingw64\bin
C:\Users\bwalk\scoop\apps\poppler\24.07.0-0\bin

Since the msys2 version (https://packages.msys2.org/package/mingw-w64-x86_64-poppler) is 24.08.0 then it appears the results above are from the scoop install as that's version 24.07.0.

FWIW I found these methods of installing poppler from this discussion https://stackoverflow.com/questions/18381713/how-to-install-poppler-on-windows

**Comment by sckott** [comment]
Thanks. Can you try running `system` with the full path to pdfimages please. E.g., `system("C:\Users\bwalk\scoop\apps\poppler\24.07.0-0\bin\pdfimages")` or whatever works on windows

**Comment by b2thewalker** [comment]
It gives me:

> system("C:\Users\bwalk\scoop\apps\poppler\24.07.0-0\bin\pdfimages")
Error: '\U' used without hex digits in character string (<input>:1:12)

To confirm this is the actual path directory I have copied path and r un again (it';s the same but with the file extension .exe), which gives the same result.

> system("C:\Users\bwalk\scoop\apps\poppler\24.07.0-0\bin\pdfimages.exe")
Error: '\U' used without hex digits in character string (<input>:1:12)

Edit: Silly me, need fwd slash, not back slash.

> system("C:/Users/bwalk/scoop/apps/poppler/24.07.0-0/bin/pdfimages.exe")
pdfimages version 24.07.0
Copyright 2005-2024 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2011, 2022 Glyph & Cog, LLC
Usage: pdfimages [options] <PDF-file> <image-root>
  -f <int>                 : first page to convert
  -l <int>                 : last page to convert
  -png                     : change the default output format to PNG
  -tiff                    : change the default output format to TIFF
  -j                       : write JPEG images as JPEG files
  -jp2                     : write JPEG2000 images as JP2 files
  -jbig2                   : write JBIG2 images as JBIG2 files
  -ccitt                   : write CCITT images as CCITT files
  -all                     : equivalent to -png -tiff -j -jp2 -jbig2 -ccitt
  -list                    : print list of images instead of saving
  -opw <string>            : owner password (for encrypted files)
  -upw <string>            : user password (for encrypted files)
  -p                       : include page numbers in output file names
  -print-filenames         : print image filenames to stdout
  -q                       : don't print any messages or errors
  -v                       : print copyright and version info
  -h                       : print usage information
  -help                    : print usage information
  --help                   : print usage information
  -?                       : print usage information
[1] 99

**Comment by sckott** [comment]
Ah cool, so it seems like if we just allow the user to set the path to pdfimages themselves, we'll be all set. Will push something soon to test out

**Comment by b2thewalker** [comment]
Cool, thanks.

BTW when I run the example you give I get this:

> x <- system.file("examples/BachmanEtal2020.pdf", package="pdfimager")
> pdimg_images(x)
Error in pdfimages_exists() : could not find function "pdfimages_exists"

I notice with this that it's looking for example within the AppData folder: 

> x
[1] "C:/Users/bwalk/AppData/Local/R/win-library/4.4/pdfimager/examples/BachmanEtal2020.pdf"

whereas when I define my own full directory of where the pdf is is simply gives x = "". So seems I'm not using the system.file() function correctly.  Do I need to put my pdf file in the "AppData/Local/R/win-library/4.4/pdfimager/" folder? Surely not?

**Comment by sckott** [comment]
The `system.file` bit is just kinda specific to examples for R packages. When files are needed for examples for functions that's a typical way to do it - because the package developer needs a way to find the path on any operating system, that function handles that. You can just give the path to wherever your file is as `x`

**Comment by sckott** [comment]
First, reinstall the package from a different branch in this repo

```r
remotes::install_github("sckott/pdfimager@user-set-path")
```

Reload the R session

Then run

```r
# I think that's the path from above that worked?
pdimg_set_path("C:/Users/bwalk/scoop/apps/poppler/24.07.0-0/bin/pdfimages.exe")
```

Then this should return `TRUE` for you

```r
has_pdfimages()
```

Then you should be able to use the other functions as expected. Do they work or no?

**Comment by b2thewalker** [comment]
Great it works. Thank you! I can't open the ppm file format, and want these images to be in jpeg or png (or whatever they were natively when put in the pdf). I see in the pdimg_help() that it says to use "-j" and "-png". How do I specify this in the function? I haven't been able to find any examples.

**Comment by sckott** [comment]
Glad it works! I'll see about using those flags and get back to you

**Comment by sckott** [comment]
You can pass flags to the ellipsis (`...`) like `pdimg_images(x, "-png")`

However, I don't' think that actually converts to png. I tried that on a pdf and I still got `.ppm` files out. You could use `magick` though:


```r
install.packages("magick")
library(magick)
image <- image_read("-png/BachmanEtal2020/img-000.ppm")
png <- image_convert(image, format = "png")
image_write(png, "out.png")
```

**Comment by b2thewalker** [comment]
Yesterday I too had tried exactly what you had, both with "-png" and then also used magick. Today I thought of using magick's format command in the pdimg_images() function and it worked i.e. pdimg_images(x, format = "-png"). :)

**Comment by sckott** [comment]
Woah, I wonder how that works. I'll put some examples in for that.

**Comment by sckott** [comment]
Okay, these changes merged to main, so you can install like `remotes::install_github("sckott/pdfimager")`

**Comment by sckott** [comment]
I forgot to mention you can also set the path to pdfimages via an env var, like 

```r
# before starting R
PDFIMAGER_PATH=C:/some/path/to/poppler/24.07.0-0/bin/pdfimages.exe R
# or set within an R session, etc.
```

I'll add that to the docs too

**Comment by b2thewalker** [comment]
Look fwd to seeing the updated docs. Not yet sure how this "PDFIMAGER_PATH=" would be set as it's not a R function in this package.

Would be great for new commers if in your README and/or Docs page that you give some recommendations on how to install Poppler because unfortunately the Poppler website doesn't address it. Took me little while to find best way to do it by trialling the methods addressed in that Stackoverflow discussion I linked earlier.

**Comment by sckott** [comment]
@b2thewalker see  https://sckott.github.io/pdfimager/#set-the-path
